// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2PK_-jYoQDlcFk5TP-9yUvH6FIGnhyqE',
    appId: '1:780867026107:web:c8ba7993268b83a09abd9e',
    messagingSenderId: '780867026107',
    projectId: 'drift-11',
    authDomain: 'drift-11.firebaseapp.com',
    storageBucket: 'drift-11.firebasestorage.app',
    measurementId: 'G-QWDFT2CL2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3uTb3WljJoBhgyFcRYWGGbyj9qkqciic',
    appId: '1:780867026107:android:007a355e3d6d7dc19abd9e',
    messagingSenderId: '780867026107',
    projectId: 'drift-11',
    storageBucket: 'drift-11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLX2XoAFYseYcT-1RUSlfhM5_eGoYO6Ck',
    appId: '1:780867026107:ios:746b9aa00c6ad7f69abd9e',
    messagingSenderId: '780867026107',
    projectId: 'drift-11',
    storageBucket: 'drift-11.firebasestorage.app',
    androidClientId: '780867026107-jsdh7v5knj4pgkijm7cpfj35b51fcuum.apps.googleusercontent.com',
    iosClientId: '780867026107-m8rf5uldjdl14lqr3lc9hdgspjjcho7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.drift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLX2XoAFYseYcT-1RUSlfhM5_eGoYO6Ck',
    appId: '1:780867026107:ios:746b9aa00c6ad7f69abd9e',
    messagingSenderId: '780867026107',
    projectId: 'drift-11',
    storageBucket: 'drift-11.firebasestorage.app',
    androidClientId: '780867026107-jsdh7v5knj4pgkijm7cpfj35b51fcuum.apps.googleusercontent.com',
    iosClientId: '780867026107-m8rf5uldjdl14lqr3lc9hdgspjjcho7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.drift',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2PK_-jYoQDlcFk5TP-9yUvH6FIGnhyqE',
    appId: '1:780867026107:web:aa512887e6c246259abd9e',
    messagingSenderId: '780867026107',
    projectId: 'drift-11',
    authDomain: 'drift-11.firebaseapp.com',
    storageBucket: 'drift-11.firebasestorage.app',
    measurementId: 'G-MBD5HMJR6M',
  );

}